### ISSUE TITLE
Fix example link the API documentation

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-telemetry-sdk-c#45]
The examples link in the [API documentation](https://newrelic.github.io/newrelic-telemetry-sdk-c/) needs to be fixed. The API documentation is created automatically using the [README](https://github.com/newrelic/newrelic-telemetry-sdk-c#readme) and did not convert the `examples` link correctly in the `Getting Started` section. You can see below, the `[examples](examples)` should be [examples](https://newrelic.github.io/newrelic-telemetry-sdk-c/examples.html).

```
Getting Started
In order to send telemetry data to New Relic APIs, you will need an Insert API key. to find out how to generate this key, see our docs.

Refer to the API documentation and to the [examples](examples).

This is a simple application that sends a single span:
```

**Comment by mfulb** [comment]
The link appears to work now so closing.
